### ISSUE TITLE
Problems with auth tokens!!!!!

### ISSUE THREAD

**Issue by jordy-ricardo25** [ETSA-Labs/Comedor-Politecnico#13]
My token has expired, due to a change in my account, the app should not die, it should just ask me to log in again 😒

![image](https://github.com/user-attachments/assets/d93a1665-d08d-482c-9cf0-30a3d8faffca)

**Comment by jordy-ricardo25** [comment]
Do not close it, it's not resolved.

**Comment by Mikelon23** [comment]
Now its okay!!
